repos:
- repo: local
  hooks:
  - id: "check-cc-format"
    name: "[clang-format] Check for C/C++/Protobuf Format"
    entry: "./scripts/batch.py --regex-cc --flags='-n -Werror'"
    language: system
    files: ^(./)?((ccsrc)|(tests))/.*$
  - id: "check-cc-lint"
    name: "[clang-tidy] Check for CC Lint"
    entry: "./scripts/run-clang-tidy -p build -quiet $1"
    language: system
    files: ^(./)?((ccsrc)|(tests))/.*$
  - id: "cppcheck"
    name: "[cppcheck] Check for Tensorflow"
    entry: "./scripts/cppcheck-tf"
    language: system
    files: ^(./)?((ccsrc/adapters/tensorflow))/.*$
  - id: "check-py-format"
    name: "[black] Check for Python Format"
    entry: black --check
    language: system
    files: ^(./)?python/.*$
  - id: "check-py-lint"
    name: "[pylint] Check for Python Lint"
    entry: pylint
    language: system
    files: ^(./)?python/.*$
  - id: "check-cmake-format"
    name: "[cmake-format] Check for Cmake Format"
    entry: ./scripts/batch.py --binary cmake-format --regex-cmake --flags='--check'
    language: system
    files: "(^(./)?CMakeLists.txt$)|(^(./)?((ccsrc)|(tests))/.*/CMakeLists.txt$)|(^(./)?cmake/[^(third_party)].*cmake$)"
  - id: "check-cmake-lint"
    name: "[cmake-lint] Check for Cmake Lint"
    entry: ./scripts/batch.py --binary cmake-lint --regex-cmake
    language: system
    files: "(^(./)?CMakeLists.txt$)|(^(./)?((ccsrc)|(tests))/.*/CMakeLists.txt$)|(^(./)?cmake/[^(third_party)].*cmake$)"
  - id: "check-shell-lint"
    name: "[shellcheck] Check for Shell Lint"
    entry: ./scripts/shellcheck
    language: system
    files: ^(./)?scripts/.*$