name: Check CI
on:
  push:
    branches:
      - dev
      - merge
  pull_request: yes
jobs:
  create-virtualenv:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: https://github.com/actions/setup-python@v4
      id: setup-python
      continue-on-error: true
      with:
        python-version: "3.10"
    - uses: https://github.com/syphar/restore-virtualenv@v1
      id: cache-virtualenv
    - uses: https://github.com/syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
    - run: pip install -r requirements-dev.txt
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

  check-format:
    name: Format Check
    runs-on: self-hosted
    needs: create-virtualenv
    steps:
    - uses: actions/checkout@v3
    - uses: https://github.com/actions/setup-python@v4
      id: setup-python
      continue-on-error: true
      with:
        python-version: "3.10"
    - uses: https://github.com/syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - name: "[clang-format] Check for C/C++/Protobuf Format."
      id: check-cc-format
      continue-on-error: true
      run: |
        bash ./scripts/format-cc "ccsrc tests" "-n -Werror"
    - name: "[black] Check for Python Format"
      id: check-py-format
      continue-on-error: true
      run: |
        bash ./scripts/format-py python "--check --diff"
    - name: "[cmake-format] Check for Cmake Format"
      id: check-cmake-format
      continue-on-error: true
      run: |
        which cmake-format
        cmake-format --version
        cmake-format CMakeLists.txt ccsrc/**/CMakeLists.txt cmake/*.cmake --check
    - name: Check Result
      run: |
        echo "check-cc-format:" ${{ steps.check-cc-format.outcome }}
        echo "check-py-format:" ${{ steps.check-py-format.outcome }}
        echo "check-cmake-format:" ${{ steps.check-cmake-format.outcome }}
        if [[ ${{ steps.check-cc-format.outcome }} == "failure"
              || ${{ steps.check-py-format.outcome }} == "failure"
              || ${{ steps.check-cmake-format.outcome }} == "failure"
              ]]; then
          echo failure
          exit 1;
        else
          echo success
          exit 0;
        fi
  check-lint:
    name: Lint Check
    runs-on: self-hosted
    needs: create-virtualenv
    steps:
    - uses: actions/checkout@v3
    - uses: https://github.com/actions/setup-python@v4
      id: setup-python
      continue-on-error: true
      with:
        python-version: "3.10"
    - uses: https://github.com/syphar/restore-virtualenv@v1
      id: cache-virtualenv
    - name: "[cmake-lint] Check for Cmake Lint"
      id: check-cmake-lint
      continue-on-error: true
      run: |
        which cmake-lint
        cmake-lint --version
        cmake-lint CMakeLists.txt ccsrc/**/CMakeLists.txt cmake/*.cmake
    - name: "[pylint] Check for Python Lint"
      id: check-py-lint
      continue-on-error: true
      run: |
        bash ./scripts/lint-py python
    - name: "[shellcheck] Check for Shell Lint"
      id: check-shell-lint
      continue-on-error: true
      run: |
        shellcheck --version
        bash ./scripts/shellcheck ./scripts/*
    - name: "[clang-tidy] Check for CC Lint"
      id: check-cc-lint
      continue-on-error: true
      run: |
        TIDY_FLAGS="-quiet -warnings-as-errors=*" ./scripts/lint-cc "ccsrc tests"
    - name: Check Result
      run: |
        echo "check-cc-lint:" ${{ steps.check-cc-lint.outcome }}
        echo "check-py-lint:" ${{ steps.check-py-lint.outcome }}
        echo "check-cmake-lint:" ${{ steps.check-cmake-lint.outcome }}
        echo "check-shell-lint:" ${{ steps.check-shell-lint.outcome }}
        if [[ ${{ steps.check-cc-lint.outcome }} == "failure"
              || ${{ steps.check-py-lint.outcome }} == "failure"
              || ${{ steps.check-cmake-lint.outcome }} == "failure"
              || ${{ steps.check-shell-lint.outcome }} == "failure"
              ]]; then
          echo failure
          exit 1;
        else
          echo success
          exit 0;
        fi
  check-tensorflow-lint:  # require cppcheck >= 2.7
    name: Tensorflow Code Lint Check
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: "[cppcheck] Check for Tensorflow"
      id: cppcheck
      run: |
        bash ./scripts/cppcheck-tf ./ccsrc/adapters/tensorflow
