#!/usr/bin/env bash

which cppcheck
cppcheck --version

cppcheck --enable=all \
--suppress=danglingTempReference \
--suppress=missingIncludeSystem \
--suppress=missingInclude \
--suppress=unmatchedSuppression \
--inline-suppr \
-I ccsrc/adapters/include \
-I ccsrc/cluster/include \
-I ccsrc/common/include \
-I ccsrc/cost_graph/include \
-I ccsrc/DistributedIR/include \
-I ccsrc/policy/include \
--std=c++17 \
--error-exitcode=1 \
$1
